language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 7.1

branches:
  only:
    - master

env:
  - WEBFORGE=~/.webforge

before_install:
  - composer install --prefer-dist --no-interaction

before_script:
  - chmod u+x bin/webforge

script: phpunit

notifications:
  mail: p.scheit@ps-webforge.com