language: php
sudo: false

php:
  - 5.4
  - 5.5

branches:
  only:
    - master

env:
  - WEBFORGE=~/.webforge

before_install:
  - composer self-update
  - COMPOSER_ROOT_VERSION=dev-master composer install --dev --prefer-source --no-interaction

before_script:
  - chmod u+x bin/webforge

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  hipchat: 1fbdbbbaa517c485f935a6d72f1110@ps-webforge
  mail: p.scheit@ps-webforge.com