language: php
php:
  - 5.3

branches:
  only:
    - master

before_script:
  - composer self-update
  - composer --version
  - composer install --prefer-dist --dev

script: phpunit

notifications:
  irc: "irc.freenode.org#webforge"
  mail: p.scheit@ps-webforge.com