language: php
php:
  - 5.3
  
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit

notifications:
  irc: "irc.freenode.org#webforge"
  mail: p.scheit@ps-webforge.com